{{- if and .Values.credentials.apiKey .Values.credentials.appKey }}
apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  api-key: {{ .Values.credentials.apiKey | quote }}
  app-key: {{ .Values.credentials.appKey | quote }}
{{- end }}
